// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthCheck.proto

package com.github.miyasumas.grpc.sandbox.service;

public final class HealthCheckServiceProtobuf {
  private HealthCheckServiceProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HealthCheckRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sandbox.HealthCheckRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code sandbox.HealthCheckRequest}
   */
  public  static final class HealthCheckRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sandbox.HealthCheckRequest)
      HealthCheckRequestOrBuilder {
    // Use HealthCheckRequest.newBuilder() to construct.
    private HealthCheckRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HealthCheckRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest.class, com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sandbox.HealthCheckRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sandbox.HealthCheckRequest)
        com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest.class, com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest.Builder.class);
      }

      // Construct using com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckRequest_descriptor;
      }

      public com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest getDefaultInstanceForType() {
        return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest.getDefaultInstance();
      }

      public com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest build() {
        com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest buildPartial() {
        com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest result = new com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest) {
          return mergeFrom((com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest other) {
        if (other == com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sandbox.HealthCheckRequest)
    }

    // @@protoc_insertion_point(class_scope:sandbox.HealthCheckRequest)
    private static final com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest();
    }

    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckRequest>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckRequest>() {
      public HealthCheckRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new HealthCheckRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<HealthCheckRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckRequest> getParserForType() {
      return PARSER;
    }

    public com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthCheckResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sandbox.HealthCheckResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 status = 1;</code>
     */
    int getStatus();

    /**
     * <code>optional string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code sandbox.HealthCheckResponse}
   */
  public  static final class HealthCheckResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sandbox.HealthCheckResponse)
      HealthCheckResponseOrBuilder {
    // Use HealthCheckResponse.newBuilder() to construct.
    private HealthCheckResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckResponse() {
      status_ = 0;
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HealthCheckResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              status_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse.class, com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>optional int32 status = 1;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != 0) {
        output.writeInt32(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sandbox.HealthCheckResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sandbox.HealthCheckResponse)
        com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse.class, com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse.Builder.class);
      }

      // Construct using com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        message_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.internal_static_sandbox_HealthCheckResponse_descriptor;
      }

      public com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse getDefaultInstanceForType() {
        return com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse.getDefaultInstance();
      }

      public com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse build() {
        com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse buildPartial() {
        com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse result = new com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse(this);
        result.status_ = status_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse) {
          return mergeFrom((com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse other) {
        if (other == com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse.getDefaultInstance()) return this;
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ ;
      /**
       * <code>optional int32 status = 1;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 1;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sandbox.HealthCheckResponse)
    }

    // @@protoc_insertion_point(class_scope:sandbox.HealthCheckResponse)
    private static final com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse();
    }

    public static com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckResponse>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckResponse>() {
      public HealthCheckResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new HealthCheckResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<HealthCheckResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckResponse> getParserForType() {
      return PARSER;
    }

    public com.github.miyasumas.grpc.sandbox.service.HealthCheckServiceProtobuf.HealthCheckResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sandbox_HealthCheckRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sandbox_HealthCheckRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sandbox_HealthCheckResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sandbox_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021HealthCheck.proto\022\007sandbox\"\024\n\022HealthCh" +
      "eckRequest\"6\n\023HealthCheckResponse\022\016\n\006sta" +
      "tus\030\001 \001(\005\022\017\n\007message\030\002 \001(\t2`\n\022HealthChec" +
      "kService\022J\n\013HealthCheck\022\033.sandbox.Health" +
      "CheckRequest\032\034.sandbox.HealthCheckRespon" +
      "se\"\000BG\n)com.github.miyasumas.grpc.sandbo" +
      "x.serviceB\032HealthCheckServiceProtobufb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sandbox_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sandbox_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sandbox_HealthCheckRequest_descriptor,
        new java.lang.String[] { });
    internal_static_sandbox_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sandbox_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sandbox_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
